### PR TITLE
Work around a race condition when deleting slide counters

### PR DESCRIPTION
**Pull request by solvip**
If SampleMod:trim/2 gets called by a folsom_sample_slide_server after the ETS table the server is trimming has gone away, it will go into a restart loop and eventually bring down the folsom_sample_slide_sup supervisor.
This fixes that by catching badarg and stopping the erronous process normally.

### CODE REVIEW

**Comment by joewilliams** [comment]
Thanks @solvip, this looks like a good patch. Unfortunately I, as maintainer of folsom, no longer have write access to the repo. Sorry, I am not sure when or if this PR will be merged.

**Comment by solvip** [comment]
Thanks @joewilliams, too bad.  Hopefully someone else will pick this up.

**Comment by joewilliams** [comment]
Maybe @GabrielNicolasAvellaneda @dominicphillips or @sigil66 can give me access again to folsom, bear, folsom_webmachine and folsom_cowboy.

**Comment by GabrielNicolasAvellaneda** [comment]
Hey @joewilliams I don't have access too, but maybe @sigil66 or @codemoran can help.

**Comment by dominicphillips** [comment]
@joewilliams Sorry, I can't either.

**Comment by puzza007** [comment]
Is there any appetite to fork and create a separate organisation to maintain these?  I'd be happy to help out.

**Comment by solvip** [comment]
I would be happy to help as well

**Comment by joewilliams** [comment]
@puzza007 @solvip okay, I have started https://github.com/folsom-project with fresh copies of the folsom related repos (so we aren't tied in anyway). Please let anyone you know that the repo is changing.

@solvip can you please resubmit your PR over there?

**Comment by puzza007** [comment]
@joewilliams :+1:

**Comment by solvip** [comment]
:+1:  https://github.com/folsom-project/folsom/pull/1

**Pull request closed without merging**
